---
title: "___"
author: "___"
format:
  html:
    code-fold: true
    code-tools: true
    toc: true
editor: visual
lang: fr
---

<!--# Ceci est un commentaire. -->

<!--% Ceci est une consigne. Ne jamais modifier ni déplacer les consignes dans le document ! -->

<!--% Complétez le titre et le nom des auteurs (auteur1, auteur2, auteur3 et auteur 4) dans l'entête YAML.-->

## Introduction et but

<!--% Rédigez une courte introduction de 3 ou 5 phrases qui présente vos données. Ajoutez une phrase de but. Vous devez citer la bibliographie en utilisant le formatage Markdown ad hoc et en incluant votre référence au format bibtex dans le fichier references.bib. -->

... Introduction et but...

## Matériel et méthodes

<!--% Indiquez ici d'où viennent les données et aussi quel logiciel (et version) vous utilisez pour les analyses. Inspirez-vous des projets déjà réalisés. -->

...Matériel et méthodes...

## Analyses

<!--% Lisez bien les éléments devant guider votre analyse proposée dans le README.-->

```{r setup, include=FALSE}
# Nécessaire pour les tests SDD, ne pas utiliser dans un "vrai" projet
if (!"tools:tests" %in% search())
  source(here::here("tests/tools_tests.R"), attach(NULL, name = "tools:tests"))
# Configuration de l'environnement
SciViews::R("ts")
```

<!--% Ajoutez le nombre de chunks que vous souhaitez. Répartissez-vous le travail correctement. Structurez la section en partie avec des titres explicites de niveau trois.-->

```{r Importation mobility wallonia rds}

read("data/mobility_wallonia.rds") -> mob
mobw <- mob
mobw$weekdays <- weekdays(as.POSIXct(mobw$date))
mobw[mobw$weekdays == "Saturday" | mobw$weekdays == "Sunday", 2:7] <- NA # Contient que les 5 jours de la semaine
mobw_ts <- ts(mobw$retail_and_recreation_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
mobw_ts2 <- aggregate(mobw_ts, 52, FUN = collapse::fmean, ts.eps = 1/52)

# Contient que le week-end
mobWE <- mob
mobWE$weekdays <- weekdays(as.POSIXct(mobWE$date))
mobWE[mobWE$weekdays != "Saturday" & mobWE$weekdays != "Sunday", 2:7] <- NA
mobWE_ts <- ts(mobWE$retail_and_recreation_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
mobWE_ts2 <- aggregate(mobWE_ts, 52, FUN = collapse::fmean, ts.eps = 1/52)
```

```{r LOISIR}
#Semaine sans week-end
mobwts_LOISIR <- ts(mobw$retail_and_recreation_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobwts_LOISIR, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mobw_loisirs_ts
plot(mobw_loisirs_ts)
#Week-end
mobWEts_LOISIR <- ts(mobWE$retail_and_recreation_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobWEts_LOISIR, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mobWE_loisirs_ts
plot(mobWE_loisirs_ts)

#semaine compléte
mobts_LOISIR <- ts(mob$retail_and_recreation_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobts_LOISIR, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mob_loisirs_ts
plot(mob_loisirs_ts)


```

```{r Autocorrélation LOISIR}
acf(mobw_loisirs_ts)
acf(mobWE_loisirs_ts)
acf(mob_loisirs_ts)
```

```{r}
mobw_mm_loisir <- tsd(mobw_loisirs_ts, method = "average", order = 5, times = 3)
plot(mobw_mm_loisir)
mobWE_mm_loisir <- tsd(mobWE_loisirs_ts, method = "average", order = 5, times = 3)
plot(mobWE_mm_loisir)
mob_mm_loisir <- tsd(mob_loisirs_ts, method = "average", order = 5, times = 3)
plot(mob_mm_loisir)
```

```{r loisir}
mob_mts <- tseries(mob_mm_loisir)   #semaine
acf(mob_mts[, "filtered"])
acf(mob_mts[, "residuals"])

mobWE_mts <- tseries(mobWE_mm_loisir)   #WE
acf(mobWE_mts[, "filtered"])
acf(mobWE_mts[, "residuals"])

mobw_mts <- tseries(mobw_mm_loisir)   # semaine sans WE
acf(mobw_mts[, "filtered"])
acf(mobw_mts[, "residuals"])
```

```{r loisir stat slide}

loisir_loess <- stat.slide( mob_loisirs_ts, method   = "loess", s.window = 53,trend    = TRUE, robust   = TRUE )
plot(loisir_loess)

loisir_loess_WE <- stat.slide( mobWE_loisirs_ts, method   = "loess", s.window = 53,trend    = TRUE, robust   = TRUE )
plot(loisir_loess_WE)

loisir_loess_w <- stat.slide( mobw_loisirs_ts, method   = "loess", s.window = 53,trend    = TRUE, robust   = TRUE )
plot(loisir_loess_w)

```

```{r loisir spectrum }
spectrum(mob_mts,spans = c(5, 3))->spect_loisir
spectrum(mobw_mts,spans = c(5, 3))-> spect_loisir_w
spectrum(mobWE_mts,spans = c(5, 3))->spect_loisir_WE
```

```{r TRAVAIL}
mobwts_travail <- ts(mobw$workplaces_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobwts_travail, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mobw_travail_ts
plot(mobw_travail_ts)

mobWEts_travail <- ts(mobWE$workplaces_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobWEts_travail, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mobWE_travail_ts
plot(mobWE_travail_ts)
```

```{r Autocorrélation TRAVAIL}
acf(mobw_travail_ts)
acf(mobWE_travail_ts)
```

```{r RESIDENCE}
mobwts_residence <- ts(mobw$residential_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobwts_residence, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mobw_residence_ts
plot(mobw_residence_ts)

mobWEts_residence <- ts(mobWE$residential_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobWEts_residence, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mobWE_residence_ts
plot(mobWE_residence_ts)
```

```{r Autocorrélation RESIDENCE}
acf(mobw_residence_ts)
acf(mobWE_residence_ts)
```

```{r}
mobw_mm_residence <- tsd(mobw_residence_ts, method = "average", order = 5, times = 3)
plot(mobw_mm_residence)

mobWE_mm_residence <- tsd(mobWE_residence_ts, method = "average", order = 5, times = 3)
plot(mobWE_mm_residence)
```

```{r}
mobwts_transport <- ts(mobw$transit_stations_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobwts_transport, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mobw_transport_ts
plot(mobw_transport_ts)

mobWEts_transport <- ts(mobWE$transit_stations_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobWEts_transport, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mobWE_transport_ts
plot(mobWE_transport_ts)


mobts_transport <- ts(mob$transit_stations_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobts_transport, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mob_transport_ts
plot(mob_transport_ts)
```

```{r Autocorrélation TRANSPORT}
acf(mobw_transport_ts)
acf(mobWE_transport_ts)
```

## Conclusion

<!--% Lorsque toutes les analyses sont réalisées, terminez ce bloc-notes avec 3 à 6 phrases de conclusion en rapport avec ce que vous avez observé dans vos analyses. Quels sont les éléments les plus pertinents que vous retenez ? -->

...vos conclusions ici...
