---
title: "___"
author: "___"
format:
  html:
    code-fold: true
    code-tools: true
    toc: true
editor: visual
lang: fr
---

<!--# Ceci est un commentaire. -->

<!--% Ceci est une consigne. Ne jamais modifier ni déplacer les consignes dans le document ! -->

<!--% Complétez le titre et le nom des auteurs (auteur1, auteur2, auteur3 et auteur 4) dans l'entête YAML.-->

## Introduction et but

<!--% Rédigez une courte introduction de 3 ou 5 phrases qui présente vos données. Ajoutez une phrase de but. Vous devez citer la bibliographie en utilisant le formatage Markdown ad hoc et en incluant votre référence au format bibtex dans le fichier references.bib. -->

... Introduction et but...

## Matériel et méthodes

<!--% Indiquez ici d'où viennent les données et aussi quel logiciel (et version) vous utilisez pour les analyses. Inspirez-vous des projets déjà réalisés. -->

...Matériel et méthodes...

## Analyses

<!--% Lisez bien les éléments devant guider votre analyse proposée dans le README.-->

```{r setup, include=FALSE}
# Nécessaire pour les tests SDD, ne pas utiliser dans un "vrai" projet
if (!"tools:tests" %in% search())
  source(here::here("tests/tools_tests.R"), attach(NULL, name = "tools:tests"))
# Configuration de l'environnement
SciViews::R("ts", lang = "fr")
```

<!--% Ajoutez le nombre de chunks que vous souhaitez. Répartissez-vous le travail correctement. Structurez la section en partie avec des titres explicites de niveau trois.-->

{{< >}}

```{r import}
mob <- read("data/mobility_wallonia.rds")
plot(mob)
```

```{r}
acf(mob)
```

```{r}

# Calcul des jours de la semaine
mobw$weekdays <- weekdays(as.POSIXct(mobw$date))
# Les données du week-end sont remplacées par des valeurs manquantes
mobw[mobw$weekdays == "Saturday" | mobw$weekdays == "Sunday" , 2:7] <- NA 
# La série temporelle est créée (début le 15 février 2020 = 46e jour de l'année 2020)
mobw_ts <- ts(mobw$parks_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
plot(mobw_ts)
# Aggrégation par moyenne des valeurs par semaine
mobw_ts2 <- aggregate(mobw_ts, 52, FUN = collapse::fmean, ts.eps = 1/52)
plot(mobw_ts2)

```

```{r.TRANSPORT}
mobts_transport <- ts(mob$transit_stations_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobts_, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mob_TRANSPORT_ts
plot(mob_TRANSPORT_ts)

mobWEts_transport<- ts(mobWE$transit_stations_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobWEts_transport, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mobWE_transport_ts
plot(mobWE_transport_ts)
```

```{r}
mobwts_transport <- ts(mobw$transit_stations_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobwts_transport, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mobw_transport_ts
plot(mobw_transport_ts)

mobWEts_transport <- ts(mobWE$transit_stations_percent_change_from_baseline, start = c(2020, 46), frequency = 365)
aggregate(mobWEts_transport, 52, FUN = collapse::fmean, ts.eps = 1/52) ->mobWE_transport_ts
plot(mobWE_transport_ts)
```

```{r Autocorrélation TRANSPORT}
acf(mobw_transport_ts)
acf(mobWE_transport_ts)
```

```{r}

```

## Conclusion

<!--% Lorsque toutes les analyses sont réalisées, terminez ce bloc-notes avec 3 à 6 phrases de conclusion en rapport avec ce que vous avez observé dans vos analyses. Quels sont les éléments les plus pertinents que vous retenez ? -->

...vos conclusions ici...
